# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EV2bBUFiUr75RN1Y1y5UmuUd3nV5PE6
"""

import streamlit as st
import pickle
import pandas as pd
model = pickle.load(open('tips_model.pkl','rb'))
st.title('Tips Prediction App')
total_bill = st.number_input('Total Bill')
size = st.number_input('Size')
sex = st.selectbox('Sex',['Male','Female'])
smoker =st.selectbox('Smoker',['Yes','No'])
day = st.selectbox('Day',['Thur','Fri','Sat','Sun'])
time = st.selectbox('Time',['Lunch','Dinner'])
input_data = pd.DataFrame({'total_bill':[total_bill],'size':[size],'sex':[sex],'smoker':[smoker],'day':[day],'time':[time]})
if st.button("Predict Tip"):
    prediction = model.predict(input_data)
    st.success(f"The predicted tip :{prediction[0]:2f}")